// <auto-generated />
using System;
using CloudApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CloudApi.Migrations
{
    [DbContext(typeof(UroContext))]
    [Migration("20220528203035_MakeDeviceAttachableToHome")]
    partial class MakeDeviceAttachableToHome
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0-preview.4.22229.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CommonData.Model.Entity.Component", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("HardwareLayoutId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HardwareLayoutId");

                    b.ToTable("Components");
                });

            modelBuilder.Entity("CommonData.Model.Entity.ComponentState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("ComponentId")
                        .HasColumnType("int");

                    b.Property<int?>("DeviceId")
                        .HasColumnType("int");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsOn")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("ComponentId");

                    b.HasIndex("DeviceId");

                    b.ToTable("ComponentStates");

                    b.HasDiscriminator<string>("Discriminator").HasValue("ComponentState");
                });

            modelBuilder.Entity("CommonData.Model.Entity.Device", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("HomeId")
                        .HasColumnType("int");

                    b.Property<int?>("LayoutId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RoomId")
                        .HasColumnType("int");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("HomeId");

                    b.HasIndex("LayoutId");

                    b.HasIndex("RoomId");

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("CommonData.Model.Entity.HardwareLayout", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ModelNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("HardwareLayouts");
                });

            modelBuilder.Entity("CommonData.Model.Entity.Home", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Homes");
                });

            modelBuilder.Entity("CommonData.Model.Entity.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HashedPassword")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Persons");
                });

            modelBuilder.Entity("CommonData.Model.Entity.Pin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("ComponentId")
                        .HasColumnType("int");

                    b.Property<string>("Descriptor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Direction")
                        .HasColumnType("int");

                    b.Property<int>("HwPinNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ComponentId");

                    b.ToTable("Pins");
                });

            modelBuilder.Entity("CommonData.Model.Entity.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("HomeId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("HomeId");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("HomePerson", b =>
                {
                    b.Property<int>("ConnectedHomesId")
                        .HasColumnType("int");

                    b.Property<int>("ResidentsId")
                        .HasColumnType("int");

                    b.HasKey("ConnectedHomesId", "ResidentsId");

                    b.HasIndex("ResidentsId");

                    b.ToTable("HomePerson");
                });

            modelBuilder.Entity("CommonData.Model.Entity.RgbComponentState", b =>
                {
                    b.HasBaseType("CommonData.Model.Entity.ComponentState");

                    b.Property<int>("BValue")
                        .HasColumnType("int");

                    b.Property<int>("GValue")
                        .HasColumnType("int");

                    b.Property<int>("RValue")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("RgbComponentState");
                });

            modelBuilder.Entity("CommonData.Model.Entity.Component", b =>
                {
                    b.HasOne("CommonData.Model.Entity.HardwareLayout", null)
                        .WithMany("AttachedComponents")
                        .HasForeignKey("HardwareLayoutId");
                });

            modelBuilder.Entity("CommonData.Model.Entity.ComponentState", b =>
                {
                    b.HasOne("CommonData.Model.Entity.Component", "Component")
                        .WithMany()
                        .HasForeignKey("ComponentId");

                    b.HasOne("CommonData.Model.Entity.Device", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId");

                    b.Navigation("Component");

                    b.Navigation("Device");
                });

            modelBuilder.Entity("CommonData.Model.Entity.Device", b =>
                {
                    b.HasOne("CommonData.Model.Entity.Home", "Home")
                        .WithMany()
                        .HasForeignKey("HomeId");

                    b.HasOne("CommonData.Model.Entity.HardwareLayout", "Layout")
                        .WithMany()
                        .HasForeignKey("LayoutId");

                    b.HasOne("CommonData.Model.Entity.Room", "Room")
                        .WithMany("Devices")
                        .HasForeignKey("RoomId");

                    b.Navigation("Home");

                    b.Navigation("Layout");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("CommonData.Model.Entity.Pin", b =>
                {
                    b.HasOne("CommonData.Model.Entity.Component", "Component")
                        .WithMany("Pins")
                        .HasForeignKey("ComponentId");

                    b.Navigation("Component");
                });

            modelBuilder.Entity("CommonData.Model.Entity.Room", b =>
                {
                    b.HasOne("CommonData.Model.Entity.Home", "Home")
                        .WithMany()
                        .HasForeignKey("HomeId");

                    b.Navigation("Home");
                });

            modelBuilder.Entity("HomePerson", b =>
                {
                    b.HasOne("CommonData.Model.Entity.Home", null)
                        .WithMany()
                        .HasForeignKey("ConnectedHomesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CommonData.Model.Entity.Person", null)
                        .WithMany()
                        .HasForeignKey("ResidentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CommonData.Model.Entity.Component", b =>
                {
                    b.Navigation("Pins");
                });

            modelBuilder.Entity("CommonData.Model.Entity.HardwareLayout", b =>
                {
                    b.Navigation("AttachedComponents");
                });

            modelBuilder.Entity("CommonData.Model.Entity.Room", b =>
                {
                    b.Navigation("Devices");
                });
#pragma warning restore 612, 618
        }
    }
}
